3. Pump_sensor_data dataset: sensor.csv

220319 samples

sensor.csv (108.9MB)

the last column is label includes normal and 
recovering (its range is 18101~17158,27622~24513,70632~69321,78397~77793,136432~128043,141174~141134,166517~166443)

Context

I have a friend who working in a small team that taking care of water pump of a small area far from big town, there are 7 system failure in last year. Those failure cause huge problem to many people and also lead to some serious living problem of some family. The team can't see any pattern in the data when the system goes down, so they are not sure where to put more attention.

Since I believe in using data to solve problem, I ask him to provide available sensor data and hope that someone here can help.
Content

The data are from all available sensor, all of them are raw value. Total sensor are 52 unit.
Acknowledgements

Thanks to my friend and his team for sharing this data
Inspiration

I hope that we can predict next failure before it's happen

https://www.kaggle.com/nphantawee/pump-sensor-data

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('./sensor.csv').drop('Unnamed: 0',axis=1)
data

,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,2018-04-01 00:00:00,2.465394,47.09201,53.211800,46.310760,634.375000,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,2018-04-01 00:01:00,2.465394,47.09201,53.211800,46.310760,634.375000,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2018-04-01 00:02:00,2.444734,47.35243,53.211800,46.397570,638.888900,73.54598,13.32465,16.03733,15.61777,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,2018-04-01 00:03:00,2.460474,47.09201,53.168400,46.397568,628.125000,76.98898,13.31742,16.24711,15.69734,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,2018-04-01 00:04:00,2.445718,47.13541,53.211800,46.397568,636.458300,76.58897,13.35359,16.21094,15.69734,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220315,2018-08-31 23:55:00,2.407350,47.69965,50.520830,43.142361,634.722229,64.59095,15.11863,16.65220,15.65393,...,38.28125,68.287030,52.37268,48.32176,41.087960,212.3843,153.64580,NaN,231.1921,NORMAL
220316,2018-08-31 23:56:00,2.400463,47.69965,50.564240,43.142361,630.902771,65.83363,15.15480,16.70284,15.65393,...,38.28125,66.840280,50.63657,48.03241,40.798610,213.8310,156.25000,NaN,231.1921,NORMAL
220317,2018-08-31 23:57:00,2.396528,47.69965,50.520830,43.142361,625.925903,67.29445,15.08970,16.70284,15.69734,...,39.06250,65.393520,48.90046,48.03241,40.798610,217.3032,155.38190,NaN,232.0602,NORMAL
220318,2018-08-31 23:58:00,2.406366,47.69965,50.520832,43.142361,635.648100,65.09175,15.11863,16.56539,15.74074,...,40.62500,64.236110,47.74306,48.32176,40.509258,222.5116,153.93520,NaN,234.0856,NORMAL
220319,2018-08-31 23:59:00,2.396528,47.69965,50.520832,43.142361,639.814800,65.45634,15.11863,16.65220,15.65393,...,41.40625,62.789350,46.29630,48.90046,40.219910,227.4306,150.46300,NaN,234.0856,NORMAL

In [2]:
data.isnull().sum()

timestamp              0
sensor_00          10208
sensor_01            369
sensor_02             19
sensor_03             19
sensor_04             19
sensor_05             19
sensor_06           4798
sensor_07           5451
sensor_08           5107
sensor_09           4595
sensor_10             19
sensor_11             19
sensor_12             19
sensor_13             19
sensor_14             21
sensor_15         220320
sensor_16             31
sensor_17             46
sensor_18             46
sensor_19             16
sensor_20             16
sensor_21             16
sensor_22             41
sensor_23             16
sensor_24             16
sensor_25             36
sensor_26             20
sensor_27             16
sensor_28             16
sensor_29             72
sensor_30            261
sensor_31             16
sensor_32             68
sensor_33             16
sensor_34             16
sensor_35             16
sensor_36             16
sensor_37             16
sensor_38             27
sensor_39             27
sensor_40             27
sensor_41             27
sensor_42             27
sensor_43             27
sensor_44             27
sensor_45             27
sensor_46             27
sensor_47             27
sensor_48             27
sensor_49             27
sensor_50          77017
sensor_51          15383
machine_status         0
dtype: int64

The value of the sensor_15 column is completely empty, and it is directly eliminated. Null values of other columns are filled backwards.

In [3]:
data.drop('sensor_15',axis=1,inplace=True)
data.fillna(method='ffill',inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220320 entries, 0 to 220319
Data columns (total 53 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   timestamp       220320 non-null  object
 1   sensor_00       220320 non-null  float64
 2   sensor_01       220320 non-null  float64
 3   sensor_02       220320 non-null  float64
 4   sensor_03       220320 non-null  float64
 5   sensor_04       220320 non-null  float64
 6   sensor_05       220320 non-null  float64
 7   sensor_06       220320 non-null  float64
 8   sensor_07       220320 non-null  float64
 9   sensor_08       220320 non-null  float64
 10  sensor_09       220320 non-null  float64
 11  sensor_10       220320 non-null  float64
 12  sensor_11       220320 non-null  float64
 13  sensor_12       220320 non-null  float64
 14  sensor_13       220320 non-null  float64
 15  sensor_14       220320 non-null  float64
 16  sensor_16       220320 non-null  float64
 17  sensor_17       220320 non-null  float64
 18  sensor_18       220320 non-null  float64
 19  sensor_19       220320 non-null  float64
 20  sensor_20       220320 non-null  float64
 21  sensor_21       220320 non-null  float64
 22  sensor_22       220320 non-null  float64
 23  sensor_23       220320 non-null  float64
 24  sensor_24       220320 non-null  float64
 25  sensor_25       220320 non-null  float64
 26  sensor_26       220320 non-null  float64
 27  sensor_27       220320 non-null  float64
 28  sensor_28       220320 non-null  float64
 29  sensor_29       220320 non-null  float64
 30  sensor_30       220320 non-null  float64
 31  sensor_31       220320 non-null  float64
 32  sensor_32       220320 non-null  float64
 33  sensor_33       220320 non-null  float64
 34  sensor_34       220320 non-null  float64
 35  sensor_35       220320 non-null  float64
 36  sensor_36       220320 non-null  float64
 37  sensor_37       220320 non-null  float64
 38  sensor_38       220320 non-null  float64
 39  sensor_39       220320 non-null  float64
 40  sensor_40       220320 non-null  float64
 41  sensor_41       220320 non-null  float64
 42  sensor_42       220320 non-null  float64
 43  sensor_43       220320 non-null  float64
 44  sensor_44       220320 non-null  float64
 45  sensor_45       220320 non-null  float64
 46  sensor_46       220320 non-null  float64
 47  sensor_47       220320 non-null  float64
 48  sensor_48       220320 non-null  float64
 49  sensor_49       220320 non-null  float64
 50  sensor_50       220320 non-null  float64
 51  sensor_51       220320 non-null  float64
 52  machine_status  220320 non-null  object
dtypes: float64(51), object(2)
memory usage: 89.1+ MB

In [4]:
X = data.drop(['timestamp','machine_status'],axis=1)
y = data['machine_status']

In [5]:
# Use PCA to reduce to 32 dimensions
from sklearn.decomposition import PCA

n_components = 32
X_pca = PCA(n_components = n_components).fit_transform(X)

print('X_pca.shape',X_pca.shape)

X_pca.shape (220320, 32)

In [6]:
X_pca

array([[ 106.75215174,  286.35906999, -234.90506577, ...,  -11.84042787,
           1.32770163,   -5.13347092],
       [ 106.75215174,  286.35906999, -234.90506577, ...,  -11.84042787,
           1.32770163,   -5.13347092],
       [  65.80788734,  296.18194596, -249.37596674, ...,  -11.84985992,
           0.77875574,   -4.42152901],
       ...,
       [-385.43641867, -560.91770256,   -6.36084786, ...,  -26.08051707,
          -7.44183148,    1.64697598],
       [-370.68718814, -567.19100281,   -3.5766931 , ...,  -25.06883425,
          -7.44321066,    4.49573573],
       [-383.57895032, -565.97313507,   -4.5890115 , ...,  -27.35837421,
          -7.00380742,    2.21433198]])

In [7]:
y = y.map({'NORMAL':0,'RECOVERING':1,'BROKEN':2})
y.value_counts()

0    205836
1     14477
2         7
Name: machine_status, dtype: int64

The categories are extremely unbalanced and the training effect may be poor.

In [8]:
# Divide training and test sets
from sklearn.model_selection import train_test_split

x_pca_train,x_pca_test,y_train,y_test = train_test_split(X_pca,y,test_size=0.2,random_state=11,stratify=y)

In [9]:
# One-Hot
import keras

y_train = keras.utils.to_categorical(y_train, 3)
y_test = keras.utils.to_categorical(y_test, 3)

Using TensorFlow backend.

In [10]:
#  Build a full neural network
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop

model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(32,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 512)               16896
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 1539
=================================================================
Total params: 281,091
Trainable params: 281,091
Non-trainable params: 0
_________________________________________________________________

In [11]:
model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

history = model.fit(x_pca_train, y_train,
                    batch_size=32,
                    epochs=10,
                    verbose=1,
                    validation_data=(x_pca_test, y_test))

Train on 176256 samples, validate on 44064 samples
Epoch 1/10
176256/176256 [==============================] - 28s 159us/step - loss: 0.2097 - accuracy: 0.9934 - val_loss: 0.0333 - val_accuracy: 0.9971
Epoch 2/10
176256/176256 [==============================] - 27s 151us/step - loss: 0.0516 - accuracy: 0.9971 - val_loss: 0.0318 - val_accuracy: 0.9990
Epoch 3/10
176256/176256 [==============================] - 28s 160us/step - loss: 0.0403 - accuracy: 0.9978 - val_loss: 0.0314 - val_accuracy: 0.9990
Epoch 4/10
176256/176256 [==============================] - 27s 154us/step - loss: 0.0271 - accuracy: 0.9983 - val_loss: 0.0374 - val_accuracy: 0.9980
Epoch 5/10
176256/176256 [==============================] - 27s 155us/step - loss: 0.0262 - accuracy: 0.9983 - val_loss: 0.0152 - val_accuracy: 0.9989
Epoch 6/10
176256/176256 [==============================] - 27s 153us/step - loss: 0.0210 - accuracy: 0.9986 - val_loss: 0.0238 - val_accuracy: 0.9985
Epoch 7/10
176256/176256 [==============================] - 27s 152us/step - loss: 0.0231 - accuracy: 0.9987 - val_loss: 0.0213 - val_accuracy: 0.9986
Epoch 8/10
176256/176256 [==============================] - 27s 152us/step - loss: 0.0233 - accuracy: 0.9986 - val_loss: 0.0388 - val_accuracy: 0.9979
Epoch 9/10
176256/176256 [==============================] - 27s 153us/step - loss: 0.0245 - accuracy: 0.9988 - val_loss: 0.0138 - val_accuracy: 0.9992
Epoch 10/10
176256/176256 [==============================] - 27s 152us/step - loss: 0.0202 - accuracy: 0.9988 - val_loss: 0.0144 - val_accuracy: 0.9991

In [12]:
score = model.evaluate(x_pca_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.014350418188542246
Test accuracy: 0.9990695118904114